apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-service-ingress
  namespace: devops-tools
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/rewrite-target: /jenkins
spec:
  rules:
    - http:
        paths:
          - path: /jenkins
            pathType: Prefix
            backend:
              service:
                name: jenkins-service
                port:
                  number: 8080